version: '3.8'

services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: receipt-processor-backend
    restart: unless-stopped
    ports:
      - "${BACKEND_PORT:-5001}:5001"
    environment:
      - NODE_ENV=production
      - PORT=5001
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:3000}
    volumes:
      - receipt-uploads:/app/uploads
    networks:
      - receipt-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: receipt-processor-frontend
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT:-3000}:80"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL:-http://localhost:5001/api}
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - receipt-network

volumes:
  receipt-uploads:
    driver: local

networks:
  receipt-network:
    driver: bridge

